apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rsqx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rsqx
    app.kubernetes.io/part-of: tkrw-pr712-0075-0019-app
  name: devfile-sample-rsqx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rsqx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rsqx
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-rsqx@sha256:48ffef42de272e85ad9ab213336c8e4e5fc9284d23fa6663e7e37cbf6a7fcc42
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
